config/routes.rb
Promoweb::Application.routes.draw do

  get 'products/sitemap' => 'products#sitemap'
  get 'products/rss' => 'products#rss'
  get 'products/newrss' => 'products#newrss'
  resources :products, :controller => 'admin::Products', :except => [:show] do
    member do
      get 'chart'
    end
  end
  match 'products/admin/autocomplete_supplier_name' => 'admin::Products#autocomplete_supplier_name'

  get 'products/:id(.:format)' => 'products#show'
  get 'products/:id(.:format)/images' => 'products#images', :as => 'images_project'
  get 'products/main/:iid' => redirect('/products/%{iid}')

  match 'admin' => 'admin::Users#login', :via => :get, :as => 'admin_login'
  match 'admin' => 'admin::Users#auth', :via => :post
  namespace 'admin' do
    resource :orders do
      %w(person_name company_name email_addresses phone_numbers).each do |name|
        get "autocomplete_customer_#{name}", :on => :collection
      end
      get 'create_email' # needed by Thunderbird plugin on NEW CUSTOMER
      get 'find'
      post 'find_apply'
      get 'contact_search'
      post 'contact_find'
      post 'variant_change'
      post 'set'
      post 'auto_complete_generic'
      
      get 'order_item_remove'
      get 'order_item_entry_insert'
      get 'order_item_decoration_insert'
      get 'order_entry_insert'

      get 'shipping_get'
      post 'shipping_set'

      get 'po'
      get 'purchase_mark'
    end

    resources :employees, :only => [:index, :show] do
      member do
        put 'apply_commission'
      end
    end
    resources :suppliers

    resources :users do
      collection do
        get 'logout'
        get 'password'
        post 'password' => 'users#password_set'
      end
      resources :phones, :only => [:index, :create, :destroy]
    end

    resources :phone, :only => [:edit]

    %w(paths calls inbound).each do |name|
      match "access/#{name}" => "access##{name}"
    end

    %w(qbwc quickbooks_blocked quickbooks_set other bitcoind).each do |name|
      match "system/#{name}" => "system##{name}"
    end

    resources :categories, :only => [:update, :destroy] do
      collection do
        post 'product_add'
        post 'product_remove'
        get 'auto_complete_for_path'
        get 'auto_complete_for_google_category'
      end

      member do
        put 'add'
        post 'product_remove'
      end
    end

    resources :prospect, :only => [:index, :show] do
    end
  end

  root :to => 'categories#home'

  get 'sitemaps' => 'general#sitemaps'
  get 'sitemap.xml' => 'general#sitemaps'
  get 'categories/sitemap' => 'categories#sitemap'

  get 'categories/map' => 'categories#map'
  get 'categories/*path' => 'categories#main'
  get 'categories' => 'categories#main'

  get 'search' => 'search#index'

  get 'static/:action', :controller => 'static'

  match 'order/:name' => 'orders#legacy_redirect'
  resources :orders, :only => [:index, :show] do
    collection do
      post 'add' => 'order_items#add'
      get 'location_from_postalcode_ajax'
    end

    member do
      get 'status'
      get 'items'
      post 'items'
      get 'info'
      post 'info'
      get 'contact'
      post 'contact'
      get 'artwork'
      get 'payment'
      post 'payment_submit'
      get 'payment_creditcard'
      post 'payment_creditcard'
      post 'payment_bitcoin'
      get 'payment_bitcoin_qr'
      
      get 'payment_sendcheck'
      post 'payment_sendcheck'
      
      post 'payment_use'
      post 'payment_remove'

      get 'review'
      get 'acknowledge_order'
      post 'acknowledge_order'
      get 'acknowledge_artwork'
      post 'acknowledge_artwork'

      get 'invoices'

      post 'artwork_add'
      post 'artwork_edit'
      get 'artwork_remove'

      namespace :admin do
        get 'items'
        get 'email'
        get 'access'
        delete 'destroy'

        get 'autocomplete_order_item_entry_description'
        get 'autocomplete_order_item_decoration_description'

        post 'tax_type'

        post 'duplicate'
        post 'item_duplicate'
        post 'restore'
        
        post 'payment_apply'
        post 'own'

        put 'purchase_create'
        post 'purchase_mark'
        delete 'purchase_delete'

        put 'invoice_create'
        delete 'invoice_destroy'

        delete 'task_revoke'
        put 'task_execute'
        post 'task_comment'

        get 'contact_merge'
        put 'contact_merge'

        delete 'permission_revoke'
      end
    end

    resources :items, :only => [:destroy], :controller => 'order_items'

    resource :artwork, :controller => 'artwork', :only => [] do
      post 'edit'
      scope :module => :admin do
        post 'drop_decoration'
        post 'drop_artwork'
        post 'group_new'
        post 'group_destroy'
        post 'make_proof'
        get 'inkscape'
      end
    end

    resources :artwork, :only => [:destroy, :create] do
      member do
        scope :module => :admin do
          post 'mark'
        end
      end
    end
  end

  QbwcController # QbwcRouter in qbwc_controller.rb
  match "qbwc/api" => QbwcRouter.new('qbwc'), :via => [:get, :post], :defaults => { :controller => 'qbwc', :action => '_action' }, :format => false

  match '/phone/:action(/:id)' => 'Phone'

  match '/e1_:addr.ini' => 'phone#unidata', :constraints => { :addr => /[0-9a-f]{12}/ }
end

app/controllers/admin/employee_controller.rb
class Admin::EmployeeController <  Admin::BaseController
private
  def calculate
    if params[:id] and params[:id] != @user.id
      @user = User.find(params[:id])
    end

    if @permissions.include?('Super')
      @employees = User.find(:all, :conditions => 'commission IS NOT NULL', :order => 'name')
      unless @user.commission
        @user = @employees.first
      end
    end

    @closed_orders = @user.orders.find(:all, :order => 'orders.id DESC',
                                :include => :tasks_active,
                                :conditions => "closed AND NOT orders.settled AND order_tasks.type = 'CompleteOrderTask'")

    @total_profit = @closed_orders.inject(Money.new(0)) do |m, o|
      m += o.total_price_cache - o.total_cost_cache
      m
    end

    @commissions = @user.commissions
#    @total_settled = @commissions.inject(Money.new(0)) { |m, c| m += c.settled; m }
    @total_payed = @commissions.inject(Money.new(0)) { |m, c| m += c.payed; m }

#    @pending_settle = @total_profit - @total_settled
#    @pending_pay = (@pending_settle * (@user.commission || 0)).round_cents
  end

public
  def commission
    @title = "Commissions"
    calculate
    @acknowledged_orders = @user.orders.find(:all, :order => 'orders.id DESC',
                                :include => :tasks_active,
                                :conditions => "NOT orders.closed AND order_tasks.type = 'AcknowledgeOrderTask'")
    @acknowledged_orders -= @closed_orders

    @payed_orders = @user.orders.find(:all, :order => 'orders.id DESC',
                                     :conditions => "settled AND orders.updated_at > NOW() - '3 months'::interval")
  end

  def apply_commission
    calculate
    pay = Money.new(Float(params[:commission][:payed]))

    Commission.transaction do
      @user.commissions.create(:payed => pay,
                               :comment => params[:commission][:comment] || '')

      @closed_orders.reverse.each do |order|
        p = [order.payable - order.payed, pay].min
        pay -= p
        order.payed += p
        order.settled = (order.payed == order.payable)
        order.commission = order.commission
        order.save!
        break if pay.zero?
      end

      raise "Overpaying" unless pay.zero?
    end

    redirect_to :action => :commission, :id => params[:id]
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController <  Admin::BaseController
private
  def calculate
    if params[:id] and params[:id] != @user.id
      @user = User.find(params[:id])
    end

    if @permissions.include?('Super')
      @employees = User.find(:all, :conditions => 'commission IS NOT NULL', :order => 'name')
      unless @user.commission
        @user = @employees.first
      end
    end

    @closed_orders = @user.orders
      .where("closed").where('NOT settled')
      .where(:id => CompleteOrderTask.where('active').select(:order_id))
      .includes(:customer) # To check if employee order
      .order('orders.id DESC').all

    @total_payable = @closed_orders.inject(Money.new(0)) do |m, o|
      m + o.payable - o.payed
    end

    @payable_comment = (Time.now - 15.days).strftime("%B %Y")

    @commissions = @user.commissions
  end

public
  def index
    calculate
    redirect_to admin_employee_path(@employees.first)
  end

  def show
    @title = "Commissions"
    calculate
    @acknowledged_orders = @user.orders
      .where('NOT orders.closed')
      .where(:id => AcknowledgeOrderTask.where('active').select(:order_id))
      .includes(:customer)
      .order('orders.id DESC')

    @acknowledged_orders -= @closed_orders

    @payed_orders = @user.orders
      .where("settled AND orders.updated_at > NOW() - '3 months'::interval")
      .includes(:customer)
      .order('orders.id DESC')

    @commission = Commission.new

    logger.info("DONE")
  end

  def apply_commission
    calculate
    pay = Money.new(Float(params[:commission][:payed]))

    Commission.transaction do
      @user.commissions.create(:payed => pay,
                               :comment => params[:commission][:comment] || '')

      @closed_orders.sort_by {|o| o.payable }.each do |order|
        p = [order.payable - order.payed, pay].min
        pay -= p
        order.payed += p
        order.settled = (order.payed == order.payable)
        order.commission = order.commission
        order.save!
        break if pay.zero?
      end

      raise "Overpaying" unless pay.zero?
    end

    redirect_to :action => :show
  end
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/views/admin/employees/show.haml
- if @employees
  - for employee in @employees
    %ul
      %li
        = link_to "#{employee.name} : #{'%0.0f%' % (employee.commission * 100.0)}", :id => employee.id
        \: #{employee.orders.where('NOT closed').where(:customer_id => Customer.where("person_name != ''").select(:id)).count} Open Orders

%hr

%h1= "Commissions for #{@user.name}"

%h2 Commission Payments
= form_for @commission, :url => apply_commission_admin_employee_path(@user), :html => { :method => :put } do |comm|
  %table.grid
    %thead
      %td Date
      %td Payed
      %td Comment
    %tbody
      %tr.dyn
        %td
          %strong= format_time(Time.now, false)
        %td.money
          $
          = comm.text_field :payed, :value => @total_payable, :size => 7
        %td= comm.text_field :comment, :value => @payable_comment
        %td.null
          = submit_tag 'Apply', :confirm => 'Apply Payment?'
      - for comm in @commissions
        %tr
          %td= format_time(comm.created_at, false)
          %td.money= comm.payed.to_perty
          %td= comm.comment

- for name, orders, payed in [['Closed Orders (Payable)', @closed_orders], ['Acknowledged Orders (Likely to Pay)', @acknowledged_orders], ['Payed Orders', @payed_orders, true]]
  - unless orders.empty?
    - if payed
      %hr
    %h2= name
    %table.grid
      %thead
        %td Order
        %td Date
        %td Price
        %td Cost
        %td Profit
        %td Commission
        %td Payable
      %tbody
        - total_price = Money.new(0)
        - total_cost = Money.new(0)
        - total_profit = Money.new(0)
        - total_payable = Money.new(0)
        - for order in orders
          %tr
            %td= link_to order.id, status_order_path(order)
            %td= format_time(order.created_at, false)
            %td.money= order.total_price_cache.to_perty
            %td.money= order.total_cost_cache.to_perty
            - total_price += order.total_price_cache
            - total_cost += order.total_cost_cache
            - total_profit += order.total_profit_cache
            - total_payable += order.payable - order.payed
            %td.money= order.total_profit_cache.to_perty
            %td= "%0.0f%" % (order.commission * 100.0)
            %td.money
              = order.payable.to_perty
              - unless payed or order.payed.zero?
                (-#{order.payed.to_perty} = #{(order.payable - order.payed).to_perty})
      %tfoot
        %td.money{ :colspan => 2 } Total:
        %td.money= total_price.to_perty
        %td.money= total_cost.to_perty
        %td.money= total_profit.to_perty
        %td
        %td.money= total_payable.to_perty