config/routes.rb
Promoweb::Application.routes.draw do

  get 'products/sitemap' => 'products#sitemap'
  get 'products/rss' => 'products#rss'
  get 'products/newrss' => 'products#newrss'
  resources :products, :controller => 'admin::Products', :except => [:show] do
    member do
      get 'chart'
    end
  end
  match 'products/admin/autocomplete_supplier_name' => 'admin::Products#autocomplete_supplier_name'

  get 'products/:id(.:format)' => 'products#show'
  get 'products/:id(.:format)/images' => 'products#images', :as => 'images_project'
  get 'products/main/:iid' => redirect('/products/%{iid}')

  match 'admin' => 'admin::Users#login', :via => :get, :as => 'admin_login'
  match 'admin' => 'admin::Users#auth', :via => :post
  namespace 'admin' do
    resource :orders do
      %w(person_name company_name email_addresses phone_numbers).each do |name|
        get "autocomplete_customer_#{name}", :on => :collection
      end
      get 'create_email' # needed by Thunderbird plugin on NEW CUSTOMER
      get 'find'
      post 'find_apply'
      get 'contact_search'
      post 'contact_find'
      post 'variant_change'
      post 'set'
      post 'auto_complete_generic'
      
      get 'order_item_remove'
      get 'order_item_entry_insert'
      get 'order_item_decoration_insert'
      get 'order_entry_insert'

      get 'shipping_get'
      post 'shipping_set'

      get 'po'
      get 'purchase_mark'
    end

    resources :employees, :only => [:index, :show] do
      member do
        put 'apply_commission'
      end
    end
    resources :suppliers

    resources :users do
      collection do
        get 'logout'
        get 'password'
        post 'password' => 'users#password_set'
      end
      resources :phones, :only => [:index, :create, :destroy]
    end

    resources :phone, :only => [:edit]

    %w(paths calls inbound).each do |name|
      match "access/#{name}" => "access##{name}"
    end

    %w(qbwc quickbooks_blocked quickbooks_set other bitcoind).each do |name|
      match "system/#{name}" => "system##{name}"
    end

    resources :categories, :only => [:update, :destroy] do
      collection do
        post 'product_add'
        post 'product_remove'
        get 'auto_complete_for_path'
        get 'auto_complete_for_google_category'
      end

      member do
        put 'add'
        post 'product_remove'
      end
    end

    resources :prospect, :only => [:index, :show] do
    end
  end

  root :to => 'categories#home'

  get 'sitemaps' => 'general#sitemaps'
  get 'sitemap.xml' => 'general#sitemaps'
  get 'categories/sitemap' => 'categories#sitemap'

  get 'categories/map' => 'categories#map'
  get 'categories/*path' => 'categories#main'
  get 'categories' => 'categories#main'

  get 'search' => 'search#index'

  get 'static/:action', :controller => 'static'

  match 'order/:name' => 'orders#legacy_redirect'
  resources :orders, :only => [:index, :show] do
    collection do
      post 'add' => 'order_items#add'
      get 'location_from_postalcode_ajax'
    end

    member do
      get 'status'
      get 'items'
      post 'items'
      get 'info'
      post 'info'
      get 'contact'
      post 'contact'
      get 'artwork'
      get 'payment'
      post 'payment_submit'
      get 'payment_creditcard'
      post 'payment_creditcard'
      post 'payment_bitcoin'
      get 'payment_bitcoin_qr'
      
      get 'payment_sendcheck'
      post 'payment_sendcheck'
      
      post 'payment_use'
      post 'payment_remove'

      get 'review'
      get 'acknowledge_order'
      post 'acknowledge_order'
      get 'acknowledge_artwork'
      post 'acknowledge_artwork'

      get 'invoices'

      post 'artwork_add'
      post 'artwork_edit'
      get 'artwork_remove'

      namespace :admin do
        get 'items'
        get 'email'
        get 'access'
        delete 'destroy'

        get 'autocomplete_order_item_entry_description'
        get 'autocomplete_order_item_decoration_description'

        post 'tax_type'

        post 'duplicate'
        post 'item_duplicate'
        post 'restore'
        
        post 'payment_apply'
        post 'own'

        put 'purchase_create'
        post 'purchase_mark'
        delete 'purchase_delete'

        put 'invoice_create'
        delete 'invoice_destroy'

        delete 'task_revoke'
        put 'task_execute'
        post 'task_comment'

        get 'contact_merge'
        put 'contact_merge'

        delete 'permission_revoke'
      end
    end

    resources :items, :only => [:destroy], :controller => 'order_items'

    resource :artwork, :controller => 'artwork', :only => [] do
      post 'edit'
      scope :module => :admin do
        post 'drop_decoration'
        post 'drop_artwork'
        post 'group_new'
        post 'group_destroy'
        post 'make_proof'
        get 'inkscape'
      end
    end

    resources :artwork, :only => [:destroy, :create] do
      member do
        scope :module => :admin do
          post 'mark'
        end
      end
    end
  end

  QbwcController # QbwcRouter in qbwc_controller.rb
  match "qbwc/api" => QbwcRouter.new('qbwc'), :via => [:get, :post], :defaults => { :controller => 'qbwc', :action => '_action' }, :format => false

  match '/phone/:action(/:id)' => 'Phone'

  match '/e1_:addr.ini' => 'phone#unidata', :constraints => { :addr => /[0-9a-f]{12}/ }
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  include ::OrdersHelper
  
  def format_email(mail, name)
    return nil unless mail.send(name)
    mail.send(name).zip(mail.send("#{name}_addrs")).collect do |email, full|
      mail_to(email, full)
    end.join(', ')
  end

  # Kludge to fix autocomplete (REMOVE WITH JQuery Upgrade)
  def auto_complete_result(entries, field, phrase = nil)
    return unless entries
    render :partial => '/admin/orders/autocomplete', :locals => { :entries => entries, :field => field, :phrase => phrase }
  end
end

app/helpers/order_helper.rb
OrderTask

module OrderHelper
  def submit_options(commit = true)   
    output = []
    inject = [controller.class.send("#{params[:action]}_tasks").first]
    inject << RequestOrderTask if @user

    if @order.task_ready?(RequestOrderTask, inject.uniq)
      text = @user ? "Submit Revised" : "Submit"
      text += (@order.task_completed?(PaymentInfoOrderTask) ? ' Order' : ' Quote Request')
      text += ' Again' if @order.task_performed?(RequestOrderTask)
      output << submit_tag(text, :id => 'submitbtn', :class => 'button')
    end
    
    inject << RequestOrderTask
    if task = @order.task_next(@permissions, inject.uniq) { |t| t.uri } and
      output << submit_tag("Continue to #{task.status_name}", :id => 'nextbtn', :class => 'button')
    elsif commit and (!@static or @user)
      output << submit_tag("Commit")
    end
    
    output.join('<br/>or to submit as a complete order<br/>')
  end
  
  def task_button(object, hash)
    hash.collect do |name, task|
      submit_tag(name) if object.task_ready?(task)
    end
  end
  
  def link_to_task(name, task, order = @order, options = {}, html_options = {})
    if task.uri
      link_to(name, task.uri.merge(:order_id => order.id).merge(options), html_options.merge(:class => @user && task.late && 'late'))
    else
      if @user && task.late
        "<span class='late'>#{name}</span>"
      else
        name
      end
    end
  end
    
#  def form_for(object_name, *args, &proc)
#    raise ArgumentError, "Missing block" unless block_given?
#    options = args.extract_options!
#    url = options.delete(:url) || {}
#    url.merge!(:only_path => false, :protocol => "https://") unless request.protocol == "https://" or RAILS_ENV != "production"
#    concat(form_tag(url, options.delete(:html) || {}), proc.binding)
#    fields_for(object_name, *(args << options), &proc)
#    concat('</form>', proc.binding)
#  end
  
  def format_time_course(time)
    now = Time.now
    if time.year == now.year and
       time.month == now.month and
       time.day == now.day
       
      time.strftime("%I:%M %p")
    else
      time.strftime("%A %b %d" + ((time.year != now.year) ? " %Y" : ''))
    end
  end

  def valid?(object, method)
    object and object.respond_to?(method) and object.send(method) and !object.send(method).strip.empty?
  end
  
  def render_partial_null(partial_path, local_assigns = nil)
    begin
      logger.info("Partial: #{partial_path.inspect}")
      render :partial => partial_path, :locals => local_assigns
    rescue ActionView::MissingTemplate
    end
  end
  
  def text_field_predicated(object_name, method, complete_options = {})
    if @static
      instance_variable_get("@#{object_name}").send(method).to_s
    else
      if @search or @naked
        text_field_with_auto_complete object_name, method, @search ? { :value => '' } : {}, complete_options.merge({ :after_update_element => 'on_select', :url => { :action => "auto_complete_for_#{object_name}_#{method}", :customer_id => @search ? nil : @order.customer } } )
      else
        text_field object_name, method
      end
    end
  end
  
  def customer_field(name, complete_options = {})
    str = '<td>' + text_field_predicated(:customer, name, complete_options) + '</td>'
    str += '<td>' + @similar.send(name) + '</td>' if @similar
    str
  end
  
  # Lifted and modified from calendariffic plugin
  def calendar_input(text_name, text_value, text_attributes={}, image_attributes={}, id_suffix = '')
    image_name = 'start_cal'+id_suffix
    image_attributes[:name] = image_name if image_name
    image_attributes[:id] = image_name if image_name
    date_format = '%Y-%m-%d' #'%m/%d/%y'

    text_value = Date.today.strftime(date_format) if text_value.to_s.upcase.eql? 'TODAY'
    imt = image_tag('date.png', image_attributes)
    id_name = sanitize_to_id(text_name) + id_suffix
    tft = text_field_tag(text_name, text_value, text_attributes.merge(:id => id_name))
    script = %(<script language='javascript'>
Calendar.setup({
  inputField : '#{id_name}',
  ifFormat : '#{date_format}',
  button : '#{image_name}',
  weekNumbers : false,
  range : [#{yr = Time.now.year}, #{yr+1}],
/*  disableFunc : function (date) { var ref = new Date(); return date.getTime() < ref.getTime(); }*/
});
</script>)
    
    "#{tft}#{imt}#{script}"
  end

  def calendar_input_time(text_name, text_value, text_attributes={}, image_attributes={}, id_suffix = '')
    image_name = 'start_cal'+id_suffix
    image_attributes[:name] = image_name if image_name
    image_attributes[:id] = image_name if image_name
    date_format = '%Y-%m-%d %H:%M' #'%m/%d/%y'

    text_value = Date.today.strftime(date_format) if text_value.to_s.upcase.eql? 'TODAY'
    imt = image_tag('date.png', image_attributes)
    id_name = sanitize_to_id(text_name) + id_suffix
    tft = text_field_tag(text_name, text_value, text_attributes.merge(:id => id_name))
    script = %(<script language='javascript'>
Calendar.setup({
  inputField : '#{id_name}',
  ifFormat : '#{date_format}',
  showsTime : true,
  button : '#{image_name}',
  weekNumbers : false,
  range : [#{yr = Time.now.year}, #{yr+1}],
/*  disableFunc : function (date) { var ref = new Date(); return date.getTime() < ref.getTime(); }*/
});
</script>)
    
    "#{tft}#{imt}#{script}"
  end


  # Lifted from https://github.com/alloy/complex-form-examples/blob/master/app/helpers/projects_helper.rb
  # CHANGE FOR RAILS 3
  def remove_link(fields)
    out = ''
    out << fields.hidden_field(:_destroy)
#    out << link_to(image_tag('remove.png'), "##{fields.object.class.name.underscore}", :class => 'remove')
    out << link_to_function(image_tag('remove.png'), "if (confirm('Remove Item')) { $(this).up('.#{fields.object.class.name.underscore}').hide(); $(this).previous().value = '1'; }")
    out
  end
  
  # These use the current date, but they could be lots easier.
  # Maybe just keep a global counter which starts at 10 or so.
  # That would be good enough if we only build 1 new record in the controller.
  #
  # And this of course is only needed because Ryan's example uses JS to add new
  # records. If you just build a new one in the controller this is all unnecessary.
  
  def add_link(cust, name, klass)
    plural = name.pluralize
    string = render(:partial => "/order/#{name}", :locals => { :customer => cust, name.to_sym => klass.new })
    string = string.gsub(/_attributes_\d+_/, '_attributes__index__')
    string.gsub!(/attributes\]\[(\d+)\]\[/,'attributes][_index_][')
    index = $1
    javascript_tag("var #{name}_index = #{index};") + 
    (link_to_function(image_tag('add.png') + " Add #{name.split('_').collect { |s| s.capitalize}.join(' ') }") do |page|
       page << %{$('#{plural}').insert({ bottom: "#{escape_javascript string}".replace(/_index_/g, #{name}_index++) });
}
    end)
  end
end

app/helpers/orders_helper.rb
OrderTask

module OrdersHelper
  def submit_options(commit = true)   
    output = []
    inject = [controller.class.send("#{params[:action]}_tasks").first]
    inject << RequestOrderTask if @user

    if @order.task_ready?(RequestOrderTask, inject.uniq)
      text = @user ? "Submit Revised" : "Submit"
      text += (@order.task_completed?(PaymentInfoOrderTask) ? ' Order' : ' Quote Request')
      text += ' Again' if @order.task_performed?(RequestOrderTask)
      output << submit_tag(text, :id => 'submitbtn', :class => 'button')
    end
    
    inject << RequestOrderTask
    if task = @order.task_next(@permissions, inject.uniq) { |t| t.uri } and
      output << submit_tag("Continue to #{task.status_name}", :id => 'nextbtn', :class => 'button')
    elsif commit and (!@static or @user)
      output << submit_tag("Commit")
    end
    
    output.join('<br/>or to submit as a complete order<br/>')
  end
  
  def task_button(object, hash)
    hash.collect do |name, task|
      submit_tag(name) if object.task_ready?(task)
    end
  end
  
  def link_to_task(name, task, order = @order, options = {}, html_options = {})
    if task.uri
      # Nasty kludge as controller sometimes doesn't have a /.  Don't know why, should make uri mutable
      linked = task.uri.merge(:id => order.id).merge(options)
      linked.merge!(:controller => '/' + linked[:controller]) unless linked[:controller][0] == '/'
      link_to(name, linked, html_options.merge(:class => @user && task.late && 'late'))
    else
      if @user && task.late
        "<span class='late'>#{name}</span>"
      else
        name
      end
    end
  end

  def li_to_order(name, method = nil, list = nil)
    method ||= "#{name.downcase}_order"
    li_to_cur(name,
              send("#{method}_path", @order),
              [list].flatten.compact.collect { |m| send("#{m}_path", @order) })
  end
  
  def format_time_course(time)
    now = Time.now
    if time.year == now.year and
       time.month == now.month and
       time.day == now.day
       
      time.strftime("%I:%M %p")
    else
      time.strftime("%A %b %d" + ((time.year != now.year) ? " %Y" : ''))
    end
  end

  def valid?(object, method)
    object and object.respond_to?(method) and object.send(method) and !object.send(method).strip.empty?
  end
  
  def render_partial_null(partial_path, local_assigns = nil)
    begin
      logger.info("Partial: #{partial_path.inspect}")
      render :partial => partial_path, :locals => local_assigns
    rescue ActionView::MissingTemplate
    end
  end
  
  def text_field_predicated(object_name, method, options = {})
    if @static
      instance_variable_get("@#{object_name}").send(method).to_s
    else
      if @search or @naked
        autocomplete_field object_name, method, send("autocomplete_#{object_name}_#{method}_admin_orders_path"), options
      else
        text_field object_name, method, options
      end
    end
  end
  
  def customer_field(name)
    str = '<td>' + text_field_predicated(:customer, name) + '</td>'
    str += '<td>' + @similar.send(name) + '</td>' if @similar
    str
  end
  

  # Lifted from https://github.com/alloy/complex-form-examples/blob/master/app/helpers/projects_helper.br
  def remove_child_link(f)
    f.hidden_field(:_destroy) + link_to(image_tag('remove.png'), "javascript:void(0)", :class => "remove_child")
  end
 
  def add_child_link(form_builder, association, options = {})
    name = image_tag('add.png') + " Add #{association.to_s.split('_').collect { |s| s.singularize.capitalize}.join(' ') }"
    
    template = form_builder.fields_for(association,
                                       options[:object] || form_builder.object.class.reflect_on_association(association).klass.new,
                                       :child_index => "in_dex") do |f|
      render(:partial => options[:partial] || association.to_s.singularize,
             :locals => {(options[:form_builder_local] || :f) => f})
    end.gsub(/\s+/, ' ')

    link_to(name, "javascript:void(0)", :class => "add_child", :"data-template" => template, :"data-association" => association)
  end
end

app/views/admin/orders/_autocomplete.haml
%ul
  - for entry in entries
    %li= phrase ? highlight(entry[field], phrase) : h(entry[field])

app/views/admin/orders/_items_menu.haml
.tabs.nav
  %ul
    != li_to_order 'Edit', :items_admin_order
    != li_to_order 'Customer View', :items_order

app/views/admin/orders/_order_item_decoration.haml
%tr.defined.dec
  %td
    - unless @price_lock || purchase_lock
      = link_to(image_tag("remove.png"), { :action => :order_item_remove, :id => order_item_decoration.id, :klass => 'OrderItemDecoration' }, :remote => true, :class => 'remove')
    - if order_item_decoration.technique.name == 'General'
      Dec: 
      = text_field_tag "#{order_item_decoration.class}-#{order_item_decoration.id}-description", order_item_decoration.description, :size => 28, :readonly => @price_lock || purchase_lock, 'data-autocomplete' => autocomplete_order_item_decoration_description_admin_order_path(@order)
    - elsif true
      = order_item_decoration.technique.name
      for
      = text_field_tag "#{order_item_decoration.class}-#{order_item_decoration.id}-count", order_item_decoration.count, :class => 'num'
      #{order_item_decoration.technique.unit_name}(s)
  = render :partial => 'order_item_entry_tail', :locals => { :object => order_item_decoration, :purchase_lock => purchase_lock, :null => false }

app/views/admin/orders/access.html.erb
<%= render :partial => 'admin/access/paths', :locals => { :sessions => @sessions } %>

app/views/admin/orders/artwork_generate_pdf.haml
%h2 Proof Generate Error
%p= @error.message

app/views/admin/orders/items.haml
= render :partial => 'items_menu'
- last_art = Artwork.find(:first, :include => { :group => :customer }, :conditions => { 'customers.id' => @order.customer.id }, :order => 'artworks.created_at DESC')
- if last_art and last_art.has_tag?('customer')
  .late CUSTOMER UPLOADED ARTWORK
= link_to("Create Product", new_product_path(:order_id => @order.id))

- action_list = [['Sample Order', :samples => true], ['FREE Sample Order', :samples => true, :free => true ], ['ReOrder', {}], ]
- if @suppliers.collect { |s, p| p }.flatten.find { |p| p.new_record? }
  Must have PO for all items to Spec Sample or Exact ReOrder
- else
  - action_list += [['Exact ReOrder', :exact => true], ['Spec Sample Order', {:spec => true}]]
- action_list.each do |name, params|
  |
  = link_to name, duplicate_admin_order_path(@order, params), :method => :post, :confirm => "Create new #{name}"

- if @price_lock
  .admin
    The order has been Acknowledged so customer pricing can't be changed.
    = link_to 'UNLOCK', { :unlock => true }, { :confirm => 'Unlock this page to modify items even though the order has been acknowledged!!!' }
- elsif !params[:override] and @suppliers.to_a.find { |s, pl| pl.find { |p| p.locked(allowed?('Super')) } }
  .admin
    The order bills have been reconciled so it can't be changed.
    = link_to 'OVERRIDE', { :override => true}, { :confirm => 'Unlock this page to modify items even though the order bills have been reconciled!!!' }
.invoice{ :id => "order-#{@order.id}" }
  - for supplier, purchase_list in @suppliers.to_a.sort_by { |s| s.first.id }
    .supplier
      %h2
        = link_to(supplier.name, admin_supplier_path(supplier))
        \:
        - unless supplier.login_url.blank?
          = link_to('Web Login', supplier.login_url)
        - if supplier.phone
          = format_phone(supplier.phone)
        - if supplier.fax
          FAX: #{format_phone(supplier.fax)}
          = mail_to(supplier.send_email(@order.sample))
        \: Acct #{supplier.account_number}
      - for purchase in purchase_list.sort_by { |pl| (pl.id || 0) }
        .purchase
          - purchase_lock = !(params[:override] && allowed?('Super')) && purchase.locked(allowed?('Super'))
          - if purchase.new_record?
            = form_for @order, { :url => purchase_create_admin_order_path(@order, :supplier_id => supplier.id), :html => { :class => 'noauto' } } do |order|
              %h2
                Purchase Order - Create as
                - for sub in [supplier] + supplier.children
                  = submit_tag("#{sub['name']}", :onclick => "return confirm('Are you sure you want to create a PO ?')")

              - for item in purchase.items.sort_by { |i| [i.product_id, i.quantity] }
                = render :partial => 'order_item', :locals => { :item => item, :purchase_lock => purchase_lock }
          - else             
            %h2
              Purchase for
              = purchase.supplier.name
              - if purchase.purchase_order.quickbooks_ref
                (PO:
                = purchase.purchase_order.quickbooks_ref
                - if purchase.bill
                  Bill:
                  - if ReconciledItemTask.allowed?(@permissions) and !purchase.reconciled
                    = text_field_tag "Bill-#{purchase.bill.id}-quickbooks_ref", purchase.bill.quickbooks_ref, 'size' => 8, :readonly => purchase_lock
                  - else
                    = purchase.bill.quickbooks_ref                      
                )
                - if !purchase.items.find { |i| i.task_completed?(OrderSentItemTask) } and purchase.entries.empty?
                  = link_to "Delete PO", purchase_delete_admin_order_path(@order, :purchase => purchase), :method => :delete, :confirm => 'Are you sure you want to delete this PO?'
                \-
                - if url = purchase.supplier_status_url
                  %a{ :href => url } Supplier Status
              %div
                = link_to image_tag('html.png'), :action => :po, :id => purchase
                = link_to image_tag('pdf.png'), :action => :po, :id => purchase, :format => 'pdf'
            
            .purchaseaction
              - common_tasks = all_tasks = purchase.items.first.tasks_ready.collect { |t| t.class }
              - purchase.items.each { |i| t = i.tasks_ready.collect { |t| t.class }; common_tasks &= t; all_tasks |= t; }
              - common_tasks.each do |klass|
                = form_for @order, { :url => purchase_mark_admin_order_path(@order, :purchase_id => purchase.id), :html => { :method => :post, :class => 'noauto' }} do |order|
                  = hidden_field_tag(:class, klass.to_s)
                  - case klass.to_s
                  - when 'OrderSentItemTask'
                    = submit_tag "Send by #{purchase.fax? ? 'FAX' : 'eMail'} #{OrderSentItemTask.status_name}"
                    = submit_tag "Mark #{OrderSentItemTask.status_name} (Without email)"
                  - when 'ConfirmItemTask', 'ReceivedItemTask', 'AcceptedItemTask', 'ReconciledItemTask'
                    - if klass.allowed?(@permissions)
                      = submit_tag klass.status_name
                      - if klass.instance_method_names.include?('email_complete')
                        = submit_tag klass.status_name + ' (Without Email)'
                    - else
                      = klass.waiting_name
                  - when 'EstimatedItemTask', 'ShipItemTask'
                    = klass.status_name
                    - if klass == EstimatedItemTask
                      != text_field(:data, :ship_date, :class => 'shipdate ignore', :id => "data_ship_date_#{purchase.id}")
                      Days Shipping:
                      = text_field(:data, :ship_days, { :size => 3, :value => purchase.items.first.shipping && purchase.items.first.shipping.days, :class => 'ignore' })
                      = check_box :data, :ship_saturday
                      Saturday Delivery
                    - else
                      = select(:data, :carrier, ShippingRate.carriers)
                      = text_field(:data, :tracking, { :size => 20, :class => 'ignore' })
  
                    = submit_tag 'Completed'
                    = submit_tag 'Completed (Without Email)'

              - if purchase.reconciled
                %strong= ReconciledItemTask.completed_name
              - unless (partial_tasks = (all_tasks - common_tasks)).empty?
                Partially Complete:
                = partial_tasks.collect { |t| t.status_name }.join(', ')

            - for item in purchase.items.sort_by { |i| [i.product_id, i.quantity] }
              = render :partial => 'order_item', :locals => { :item => item, :purchase_lock => purchase_lock }
          - unless purchase.new_record?
            .notes
              %strong Notes for Supplier:
              = text_field_tag "Purchase-#{purchase.id}-comment", purchase.comment, :size => 80, :readonly => purchase_lock
            = render :partial => 'order', :locals => { :order => purchase, :purchase_lock => purchase_lock }
  = render :partial => 'order', :locals => { :order => @order, :purchase_lock => false }

- unless @tasks.empty? and @revokable.empty?
  %hr
  = render :partial => 'orders/pending_tasks'

app/views/admin/orders/paths.html.erb
<%= render :partial => 'admin/access/paths', :locals => { :sessions => @sessions } %>

app/views/admin/orders/po.haml
= render :partial => '/admin/orders/po'

app/views/admin/orders/show.haml
%h1
  Order Requests (
  = @orders.length
  of
  = @count
  )
= link_to((params[:closed] ? "Exclude" : "Include") + " Closed", { :closed => !params[:closed] })

%table#fatlist
  %thead
    %tr
      %th= link_to 'ID', :sort => 'id'
      %th 
      %th Customer
      %th= link_to 'Tasks Pending', :sort => 'task'
      %th Dates
  %tbody
    - for name, orders in @groups
      - if name
        %tr
          %td{ :colspan => '5' }
            %h2= "#{name} (#{orders.length})"
      - for order in orders
        %tr
          %td
            = link_to(status_order_path(order)) do
              = order.id
              - if order.sample
                %strong> S

            = surround '(', ')' do
              - pos = order.items.collect { |i| i.purchase && i.purchase.purchase_order && i.purchase.purchase_order.quickbooks_ref }.compact.uniq
              = link_to(pos.empty? ? 'NO PO' : pos.join(','), items_admin_order_path(order))

            %br
            = order.user ? order.user.name : "Unassigned"
            - if days = order.days_to_deliver
              %br
              = link_to(days < 0 ? 'PAST DUE' : "#{order.days_to_deliver} Days", info_order_path(order))
            - if order.urgent_note and !order.urgent_note.strip.empty?
              %br
              %strong= link_to order.urgent_note, info_order_path(order)
          %td
            - order.items[0..1].each do |item|
              = link_to(image_tag(item.active_images.first.image.url(:thumb)), url_for_product(item.product))

          %td
            - if allowed?('CustomerInformationTask')
              = link_to(contact_order_path(order)) do
                %div= order.customer.company_name
                %div= order.customer.person_name
            - else
              %div= order.customer.company_name
              %div= order.customer.person_name  

            - if allowed?('CustomerInformationTask')
              - for email in order.customer.email_addresses
                %div= mail_to "#{order.customer.person_name} <#{email.address}>", email.address
              - for pn in order.customer.phone_numbers
                %div #{pn.name}: #{pn.number_string}
          %td
            - now = Time.now.utc
            - included = []
            - for task in order.tasks_allowed(@permissions)
            -   next unless task.waiting_name
            -   next if included.include?(task.waiting_name)
            -   included << task.waiting_name
              %div
                = image_tag task.customer ? 'there_task.png' : 'our_task.png'
                != link_to_task(task.waiting_name, task, order)
          %td
            - if last_task = order.task_recent
              %div
                Initial Contact:
                = format_time(order.created_at)
              %div
                = last_task.completed_name
                \:
                = format_time(last_task.updated_at)
              - if order.delivery_date
                %div
                  In Hands:
                  = order.delivery_date.strftime("%A %b %d")

/= will_paginate @orders