config/routes.rb
Promoweb::Application.routes.draw do

  get 'products/sitemap' => 'products#sitemap'
  get 'products/rss' => 'products#rss'
  get 'products/newrss' => 'products#newrss'
  resources :products, :controller => 'admin::Products', :except => [:show] do
    member do
      get 'chart'
    end
  end
  match 'products/admin/autocomplete_supplier_name' => 'admin::Products#autocomplete_supplier_name'

  get 'products/:id(.:format)' => 'products#show'
  get 'products/:id(.:format)/images' => 'products#images', :as => 'images_project'
  get 'products/main/:iid' => redirect('/products/%{iid}')

  match 'admin' => 'admin::Users#login', :via => :get, :as => 'admin_login'
  match 'admin' => 'admin::Users#auth', :via => :post
  namespace 'admin' do
    resource :orders do
      %w(person_name company_name email_addresses phone_numbers).each do |name|
        get "autocomplete_customer_#{name}", :on => :collection
      end
      get 'create_email' # needed by Thunderbird plugin on NEW CUSTOMER
      get 'find'
      post 'find_apply'
      get 'contact_search'
      post 'contact_find'
      post 'variant_change'
      post 'set'
      post 'auto_complete_generic'
      
      get 'order_item_remove'
      get 'order_item_entry_insert'
      get 'order_item_decoration_insert'
      get 'order_entry_insert'

      get 'shipping_get'
      post 'shipping_set'

      get 'po'
      get 'purchase_mark'
    end

    resources :employees, :only => [:index, :show] do
      member do
        put 'apply_commission'
      end
    end
    resources :suppliers

    resources :users do
      collection do
        get 'logout'
        get 'password'
        post 'password' => 'users#password_set'
      end
      resources :phones, :only => [:index, :create, :destroy]
    end

    resources :phone, :only => [:edit]

    %w(paths calls inbound).each do |name|
      match "access/#{name}" => "access##{name}"
    end

    %w(qbwc quickbooks_blocked quickbooks_set other bitcoind).each do |name|
      match "system/#{name}" => "system##{name}"
    end

    resources :categories, :only => [:update, :destroy] do
      collection do
        post 'product_add'
        post 'product_remove'
        get 'auto_complete_for_path'
        get 'auto_complete_for_google_category'
      end

      member do
        put 'add'
        post 'product_remove'
      end
    end

    resources :prospect, :only => [:index, :show] do
    end
  end

  root :to => 'categories#home'

  get 'sitemaps' => 'general#sitemaps'
  get 'sitemap.xml' => 'general#sitemaps'
  get 'categories/sitemap' => 'categories#sitemap'

  get 'categories/map' => 'categories#map'
  get 'categories/*path' => 'categories#main'
  get 'categories' => 'categories#main'

  get 'search' => 'search#index'

  get 'static/:action', :controller => 'static'

  match 'order/:name' => 'orders#legacy_redirect'
  resources :orders, :only => [:index, :show] do
    collection do
      post 'add' => 'order_items#add'
      get 'location_from_postalcode_ajax'
    end

    member do
      get 'status'
      get 'items'
      post 'items'
      get 'info'
      post 'info'
      get 'contact'
      post 'contact'
      get 'artwork'
      get 'payment'
      post 'payment_submit'
      get 'payment_creditcard'
      post 'payment_creditcard'
      post 'payment_bitcoin'
      get 'payment_bitcoin_qr'
      
      get 'payment_sendcheck'
      post 'payment_sendcheck'
      
      post 'payment_use'
      post 'payment_remove'

      get 'review'
      get 'acknowledge_order'
      post 'acknowledge_order'
      get 'acknowledge_artwork'
      post 'acknowledge_artwork'

      get 'invoices'

      post 'artwork_add'
      post 'artwork_edit'
      get 'artwork_remove'

      namespace :admin do
        get 'items'
        get 'email'
        get 'access'
        delete 'destroy'

        get 'autocomplete_order_item_entry_description'
        get 'autocomplete_order_item_decoration_description'

        post 'tax_type'

        post 'duplicate'
        post 'item_duplicate'
        post 'restore'
        
        post 'payment_apply'
        post 'own'

        put 'purchase_create'
        post 'purchase_mark'
        delete 'purchase_delete'

        put 'invoice_create'
        delete 'invoice_destroy'

        delete 'task_revoke'
        put 'task_execute'
        post 'task_comment'

        get 'contact_merge'
        put 'contact_merge'

        delete 'permission_revoke'
      end
    end

    resources :items, :only => [:destroy], :controller => 'order_items'

    resource :artwork, :controller => 'artwork', :only => [] do
      post 'edit'
      scope :module => :admin do
        post 'drop_decoration'
        post 'drop_artwork'
        post 'group_new'
        post 'group_destroy'
        post 'make_proof'
        get 'inkscape'
      end
    end

    resources :artwork, :only => [:destroy, :create] do
      member do
        scope :module => :admin do
          post 'mark'
        end
      end
    end
  end

  QbwcController # QbwcRouter in qbwc_controller.rb
  match "qbwc/api" => QbwcRouter.new('qbwc'), :via => [:get, :post], :defaults => { :controller => 'qbwc', :action => '_action' }, :format => false

  match '/phone/:action(/:id)' => 'Phone'

  match '/e1_:addr.ini' => 'phone#unidata', :constraints => { :addr => /[0-9a-f]{12}/ }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def add
    Category.transaction do
      parent = Category.find_by_id(params[:id])
      child = Category.create(params[:category].merge(:pinned => true, :parent_id => parent.id))
      child.move_to_child_of(parent)
      child.parent = parent
      
      redirect_to :controller => '/categories', :action => :main, :path => child.path_name_list
    end
  end

  def update
    Category.transaction do
      category = Category.find(params[:id])
      category.update_attributes(params[:category])
      category.save!
    end
    redirect_to :back
  end

  def destroy
    Category.transaction do
      child = Category.find_by_id(params[:id])
      parent = child.parent
      child.destroy
    
      redirect_to :controller => '/categories', :action => :main, :path => parent.path_name_list
    end
  end

private
  def find_categories(list, phrase, limit)
    #logger.info("List: #{list.collect { |l| l.name }.join(', ')}")
    result = []
    list.to_a.find do |elem|
      next unless elem.children
      result += elem.children.find_all { |child| child.name.downcase.include?(phrase) }
      #logger.info("Result: #{result.collect { |l| l.name }.join(', ')}")
      result.length >= limit
    end
    unless result.length >= limit
      list.find do |elem|
        next unless elem.children
        result += find_categories(elem.children, phrase, limit - result.length)
        result.length >= limit
      end
    end
    result[0...limit]
  end
public

  @@google_categories = nil
  def auto_complete_for_google_category
    unless @@google_categories
      @@google_categories = File.open(File.join(Rails.root,'lib/taxonomy.en-US.txt')).collect { |l| l.strip }
      logger.info("Loaded Google Categories: #{@@google_categories.length}")
    end

    list = @@google_categories.find_all { |c| c.include?(params[:term]) }
    logger.info("Found: #{list.inspect}")

    render :json => list.collect { |s| { 'label' => s } }
  end

  def auto_complete_for_path
    @categories = [Category.root]
    path = params[:path].split('/')
    limit = 10*path.length
    path.each do |phrase|
      phrase.downcase!
      @categories = find_categories(@categories, phrase, limit)
      limit /= 10
    end

    logger.info("Cats: #{@categories}")

    render :json => @categories.collect { |s| { 'label' => s } }
  end

  def product_add
    Category.transaction do
      category = Category.find_by_path(params[:path].split('/'))
      product = Product.find(params[:id])

      unless category and product
        render :inline => "Cannot find category or product"
        return
      end
      
      category.pinned = true
      product.categories << category
    end
    redirect_to :back
  end

  def product_remove
    Category.transaction do
      category = Category.find(params[:id])
      product = Product.find(params[:product_id])
      
      product.categories.delete(category)
    end
    redirect_to :back
  end
end

app/controllers/categories_controller.rb
class LinkRenderer < WillPaginate::ActionView::LinkRenderer
  def page_number(page)
    text = @options[:page_names] ? @options[:page_names][page-1] : page.to_s
    unless page == current_page
      link(text, page, :rel => rel_value(page))
    else
      tag(:em, text, :class => 'current')
    end
  end

  def add_current_page_param(url_params, page)
    url_params[:path] = url_params[:path].split('/')[0...-1] + [page] if url_params[:path]
  end
end


class CategoriesController < ApplicationController
  before_filter :setup_context

  #caches_page :main, :home

  @@featured_items = 4
  cattr_reader :featured_items

private
  def sitemap_recurse(root, exclusive = false, list = []) 
    base = (["http://www.mountainofpromos.com/categories"] + root.path_web).join('/')
    list << { :loc => base}
    
    ([nil] + root.products_tags({:children => !exclusive})).each do |tag|
      total = root.count_products({
        :children => !exclusive,
        :tag => tag
      })
      pages = (total.to_f / (@@columns * @@rows)).ceil

      Category.order_list.each do |order|
        pages.times do |page|
          list << { :loc => 
            (["http://www.mountainofpromos.com/categories"] + root.path_web +
            [exclusive ? 'exclusive' : nil, tag, "#{order}/#{page+1}"]).compact.join('/') }
        end
      end
    end
    
    unless exclusive
      if root.count_products > 0 and root.children.count > 0
        sitemap_recurse(root, true, list)
      end
      
      root.children.each do |child|
        sitemap_recurse(child, false, list)
      end if root.children
    end
    
    list
  end
public
  
  # Google sitemap
  def sitemap
    headers['Content-Type'] = 'text/xml; charset=utf-8'  
    @links = sitemap_recurse(Category.root)
    render :template => 'sitemaps/sitemap', :layout=>false
  end

  def map

  end

  @@columns = 4
  @@rows = 5
  cattr_reader :columns, :rows
  

  # The ruby way, show as mooolasis
  def home
    @title = "Mountain of Promotions - Custom imprinted Promotional Products, Advertising Specialties, Promotional Items"
    @description = "Custom imprinted Promotional Products, Advertising Specialties, Promotional Items"

    @per_page = @@columns * @@rows

    @purposes = ['employee recognition', 'corporate gifts', 'product promotions', 'school promotions', 'educational aids', 'health and wellness programs', 'safety awareness', 'staff recognition', 'appreciation gifts']
    @keywords = ('custom imprinted embroidered debosed products ' + @purposes.join(' ')).split(' ').uniq.join(' ')

    list = []
    %w(Special Closeout).each do |tag_name|
      list += Category.root.children.collect do |cat|
        [cat, tag_name, cat.count_products(:children => true, :tag => tag_name)]
      end.sort_by { |cat, tag, count| count }.reverse[0...6]
    end

    @categories = list.sort_by { |cat, tag, count| count }[0...8].sort_by { |cat, tag, count| cat.name }

    OrderTask
    @reviews = ReviewOrderTask.find(:all, :order => 'id DESC', :limit => 10, :conditions => { :active => true })
    @reviews.delete_if do |review|
      next !review.publish unless review.publish.nil?
      false
#      sum = 0
#      num = 0
#      ReviewOrderTask.aspect_methods.each do |method|
#        rate = review.send(method).to_i
#        next unless rate
#        num += 1
#        sum += rate
#        sum = -100 if rate < 3
#      end
#      next true if sum <= (num * 3)
    end
  end

  # redirect to appropriate method
  def main   
    @path = params[:path] ? params[:path].split('/') : []
    
    # Split @path and tail at meta point
    tail = nil
    (Tag.names + Category.order_list).find do |t|
      if idx = @path.index(t)
        tail = @path[(idx)..-1]       
        @path = @path[0...idx]
        next true
      end
    end
    
    @path_web = @path    
    @path = @path.collect { |p| p.gsub('_',' ') }
    
    @exclusive = @path.last == 'exclusive'
    children = !(@exclusive && @path.pop)
    raise ::ActionController::RoutingError, "Meta category exclusive must be used with tail" if !children and !tail
       
    # Find Category
    @category = Category.find_by_path(@path)
    raise ::ActionController::RoutingError, "Category does not exist: #{@path.join('/')}" unless @category
    raise ::ActionController::RoutingError, "Category exclusive only applies to categories with children" unless children or @category.children.count > 0
       
    @title = "Custom #{@category.name} - Logo Imprinted Promotional Products"
    
    @columns = [(params[:columns] && params[:columns].to_i > 0) ? params[:columns].to_i : nil, session[:columns], @@columns].compact.first
    session[:columns] = @columns if session[:columns] || @columns != @@columns
    @rows = [(params[:rows] && params[:rows].to_i > 0) ? params[:rows].to_i : nil, session[:rows], @@rows].compact.first
    session[:rows] = @rows if session[:rows] || @rows != @@rows
    @per_page = @columns * @rows

    @context = {
      :children => children,
      :sort => 'price',
    }
    
    if tail
      list(tail)
    else
      categories
    end
  end
  
private
  def categories
    # Redirect to list view if category doesn't have children
    if @category.children.count == 0
      redirect_to :path => @path_web + %w(price 1)
      return
    end

    @per_page = @@columns * @@rows
    
    @direct_children = @category.children.sort { |l, r| l.name <=> r.name }
    direct_children_names = @direct_children.collect { |c| c.name }

    @context[:children] = false
    
    @email_subject = @category.name
    
    @description = "Custom printed #{@category.name} including "
    direct_children_names.each do |name|
      break if @description.length + name.length > 158
      @description += name + ", "
    end
    @description = @description[0..-3]
    
    @keywords = "#{@category.name} #{direct_children_names.join(' ')}"
  
    render :action => :categories
  end

  def list(tail)
    @path_tail = @path_web + tail[0...-1]

    # Parse and validate path tail
    @context.merge!(:tag => tail.shift) if Tag.names.include?(tail.first)

    raise ::ActionController::RoutingError, "Sort order required" if tail.empty?
    sort = tail.shift
    raise ::ActionController::RoutingError, "Sort order must be #{Category.order_list.join(', ')}" unless Category.valid_order?(sort)
    @context.merge!(:sort => sort)

    raise ::ActionController::RoutingError, "Page number required" if tail.empty?
    @page = tail.shift
    raise ::ActionController::RoutingError, "Page number must be numeric" unless @page.to_i.to_s == @page
    @page = @page.to_i
    raise ::ActionController::RoutingError, "Page number must be positive" unless @page > 0
  
    options = @context.merge({
      :page => @page,
      :per_page => @per_page
    })
       
    @products = @category.paginate_products(options)

    @paginate_options = {
      :renderer => 'LinkRenderer'
    }

    if sort == 'price'
      @page_names = @category.calculate_products_price_breaks(options).collect { |e| "#{e['min'].to_perty} &#8211; #{e['max'].to_perty}" }
      @paginate_options.merge!(:page_names => @page_names, :inner_window => 1)
    end    
    
    @email_subject = @category.name
    
    @description = "List of #{@products.total_entries} #{@category.name}"
    @description += ".  All products can be custom imprinted."

    render :action => :list
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def setup_home
#    products = Category.root.products_featured(:children => true, :include => :categories)
    products = Product.find(:all, :include => [:variants => [:price_groups => :order_items]],
                            :select => 'products.*', :order => 'order_items.id DESC', :limit => 20)
    
    assigned = {}
    assigned.default = []
    
    cat_hash = {}
    cat_hash.default = []    
    products.each do |prod|
      prod.categories.each do |cat|
        cat = Category.find_by_id(cat.id)
        ([Category.root] + cat.path_obj_list).each do |cat|
          cat_hash[cat] += [prod] unless cat_hash[cat].index(prod); 
        end
      end
    end
        
    list = cat_hash.to_a.sort { |l, r| l.last.size <=> r.last.size }
    
    until list.empty? or list.first.first == Category.root
      category = list.first.first
      product = list.shift.last
      
      if product.size >= 3
        assigned[category] = product
        list.delete_if do |cat, prods|
          prods.delete_if { |prod| product.index(prod) }
          prods.empty?
        end
      end
    end

    @featured = assigned.collect do |cat, lst|
      [cat, lst.uniq.sort { |l,r| l.price_min_cache <=> r.price_min_cache}]
    end.sort { |l, r| l.first.name <=> r.first.name }
    
    @featured.unshift([Category.root, list.shift.last]) unless list.empty?
    
    @limit = CategoriesController.rows * CategoriesController.columns
  end
end

app/views/categories/_category.haml
.category
  - unless context[:tag]
    .tags
      - for tag in category.products_tags(context)
        - if tag.count.to_i > 5
          = link_to image_tag("tags/#{tag.name.downcase}.png", :alt => "#{tag.name} Icon") + "#{tag.name} (#{tag.count})", :action => 'main', :path => (path + [tag.name, 'price', '1']).compact
        - else
          - product = category.find_products({:children => context[:children], :tag => tag.name, :order => 'price', :limit => 1 }).first
          = link_to image_tag("tags/#{tag.name.downcase}.png", :alt => "#{tag.name} Icon") + "#{tag.name} (#{tag.count})", url_for_product(product, category, { :tag => tag.name, :order => 'price', :children => context[:children] })

  - count = category.count_products(context)
  %a{ :href => url_for(:action => 'main', :path => (path + (to_list ? [context[:tag], 'price', '1'] : [nil])).compact), :class => 'title' }
    - if context[:tag]
      = image_tag("tags/#{context[:tag].downcase}.png", :alt => "#{context[:tag]} Icon")
      = context[:tag] + " "
    = display_name + " (#{count})"

  %table.breaks
    %tr
      - for brk in category.calculate_products_price_breaks(context.merge(:per_page => @per_page, :window => 4))
        %td
          = brk ? link_to("#{brk['min'].to_perty} to #{brk['max'].to_perty}", :action => 'main', :path => (path + [context[:tag], 'price', brk['page']]).compact) : '. . .'

  - products = category.select_products(context.merge(:limit => CategoriesController.featured_items)) unless products
  - unless products.empty?
    %table.list
      - products.in_groups_of(4) do |row|
        %tr
          - for prod in row.compact
            %td
              = render :partial => 'thumb', :locals => { :product => prod, :category => category, :context => context }

app/views/categories/_description.haml
- unless @user
  - if @category.description && !@category.description.strip.empty?
    #description= @category.description
- else
  #description.admin
    = form_for @category, { :url => add_admin_category_path(@category) } do |cat|
      = cat.text_field :name, :value => ''
      = submit_tag 'Add Category'
      - if @category.products.empty? and @category.children.empty?
        = link_to 'Remove Category', admin_category_path(@category), :method => :delete

    = form_for @category, { :url => admin_category_path(@category), :html => { :method => :put } } do |cat|
      = cat.text_area :description, :cols => 100, :rows => 4
      %br
      Google:
      = autocomplete_field :category, :google_category, auto_complete_for_google_category_admin_categories_path, { :size => 100 }
      %br
      = submit_tag 'Update'

app/views/categories/_list.haml
#gridsel
  = form_tag do
    - for name in %w(columns rows)
      = name.capitalize
      %select{ :onchange => 'location = this.options[this.selectedIndex].value;' }
        - for num in [4,5,6,7,8,9,10,name == 'rows' ? 100 : nil].compact
          <option value='#{url_for(params.merge(name => num))}'#{instance_variable_get("@#{name}") == num ? ' selected' : ''}>#{num}</option>

= will_paginate @products, @paginate_options

#list
  %table.list
    %tbody
      - @products.in_groups_of(@columns) do |row|
        %tr
          - for prod in row.compact
            %td
              = render :partial => 'categories/thumb', :locals => { :product => prod, :category => @category, :context => context }

= will_paginate @products, @paginate_options

app/views/categories/_map.haml
%ul
  - root.children.sort { |l, r| l.name <=> r.name }.each do |child|
    %li= link_to_category(child)
    - if child.children and !child.children.empty?
      = render :partial => 'map', :locals => { :root => child }

app/views/categories/_thumb.haml
- if @user && category
  = link_to image_tag('remove.png'), product_remove_admin_category_path(category, :product_id => product), :confirm => "Remove #{product.name} from #{category.path}"
%a.thumb{ :href => url_for_product(product, category, context) }
  - if image = product.product_images.find(:first, :select => "*, id NOT IN (SELECT product_image_id FROM product_images_variants JOIN variants ON variant_id = id WHERE variants.product_id = #{product.id}) AS variant", :order => 'variant DESC')
    = image_tag image.image.url(:thumb), :alt => "#{product.name} Thumbnail"
  %br
  %span.name
    - if product.respond_to?(:name_headline)
      != product.name_headline
    - else
      != product.name
  - if product.price_min_cache and product.price_max_cache
    %span.price
      = product.price_min_cache.to_perty
      to
      = product.price_max_cache.to_perty

app/views/categories/categories.haml
!= path_text

= render(:partial => 'description')

- cache do
  #categories
    = render(:partial => 'category',    :locals => { :category => @category, :display_name => "All #{@category.name == 'root' ? 'Products' : @category.name}", :path => @path_web, :to_list => true, :context => @context.merge(:children => true) })
    - for category in @direct_children
      = render(:partial => 'category',  :locals => { :category => category,  :display_name => category.name, :path => @path_web + [category.name.gsub(' ','_')], :context => @context.merge(:children => (category.children.count > 0)), :to_list => !(category.children.count > 0) })
    - if @category.count_products > 0
      = render(:partial =>  'category', :locals => { :category => @category, :display_name => "Misc. #{@category.name}", :path => @path_web + ['exclusive'], :to_list => true, :context => @context.merge(:children => false) })

app/views/categories/home.haml
- cache do
  #virtues
    %div
      %h2 Service
      %p We deliver an excellent customer service experience. If you have questions about any of the great promotional products and corporate gifts we offer, you can call or email and your question will be answered promptly by you own knowledgeable account representative who will guide you through the order process. 

    %div
      %h2 Value
      %p Our prices are some of the best in the industry and our customers always get a great deal on promotional products and without having to spend their valuable time price shopping. We guarantee our low prices – if you find a lower price, we will beat it. We are one of the few promotional product companies to offer a continuous pricing scheme – simply put, the more units you order, the less expensive they get without any artificial price breaks.
      %p In addition, a promotional product is a cost-effective and efficient way to advertise, promote your brand, grow your business, stand out at a trade show or exposition, and reward employees and customers. 
    
    %div
      %h2 Rush
      %p Need a custom imprinted product right away? We can decorate and ship many of our custom imprinted promotional products and executive gifts within 24 hours of your order – and often, at no additional charge!

    %div
      %p We have over 16,000 custom promotional products including custom tote bags, padfolios, mugs, pens and much, much more ! A promotional product makes a great employee gift, trade show item, customer incentive or customer thank-you gift .  If you need marketing ideas, an effective form of advertising, want to gain brand recognition, or simply want to stand out from the crowd and make your trade show exhibit memorable, look no further!

  #categories
    - for category, tag, count in @categories
      = render :partial => 'categories/category', :locals => { :category => category, :display_name => category.name, :path => category.path_web, :to_list => true, :context => { :children => true, :tag => tag } }

  %p 
    We have a large selection of custom imprinted promotional products with over 16,000 to choose from for events like 
    = @purposes.join(', ')

app/views/categories/list.haml
!= product_count
%h1#path
  != path_name
  %span#order
    %span
      Sort by:
    - for order in Category.order_list
      = link_to(order.capitalize, { :path => (@path_web + [@context[:tag], order, @page]).compact }, { :class => (@context[:sort] == order) ? 'sel' : nil })

- unless @exclusive
  = render(:partial => 'description')

= render :partial => 'list', :locals => { :products => @products, :columns => @columns, :category => @category, :context => @context }

app/views/categories/map.haml
%h1 Site Map
%h2 Categories
= render :partial => 'map', :locals => { :root => Category.root }

%h2 Information
%ul
  - StaticController.pages.each do |name, tail|
    %li= link_to name, { :controller => 'static', :action => tail }